name: homl3
channels:
  - conda-forge
  - defaults
dependencies:
  - box2d-py=2.3  # used only in chapter 18, exercise 8
  - ffmpeg=5.1  # used only in the matplotlib tutorial to generate animations
  - graphviz  # used only in chapter 6 for dot files
  - python-graphviz  # used only in chapter 6 for dot files
  - ipython=8.5  # a powerful Python shell
  - ipywidgets=8.0  # optionally used only in chapter 12 for tqdm in Jupyter
  - joblib=1.1  # used only in chapter 2 to save/load Scikit-Learn models
  - jupyterlab=3.4  # to edit and run Jupyter notebooks
  - matplotlib=3.5  # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime=3.1  # optional tool to diff Jupyter notebooks
  - nltk=3.6  # optionally used in chapter 3, exercise 4
  - numexpr=2.8  # used only in the Pandas tutorial for numerical expressions
  - numpy=1.23  # Powerful n-dimensional arrays and numerical computing tools
  - pandas=1.4  # data analysis and manipulation tool
  - pillow=9.2  # image manipulation library, (used by matplotlib.image.imread)
  - pip  # Python's package-management system
  - py-xgboost=1.6  # used only in chapter 6 for optimized Gradient Boosting
  - pydot=1.4  # used only for in chapter 10 for tf.keras.utils.plot_model()
  - python=3.10  # your beloved programming language! :)
  - requests=2.28  # used only in chapter 19 for REST API queries
  - scikit-learn=1.1  # machine learning library
  - scipy=1.9  # scientific/technical computing library
  - statsmodels=0.13  # used only in chapter 15 for time series analysis
  - tqdm=4.64  # used only in chapter 12 to display nice progress bars
  - wheel  # built-package format for pip
  - widgetsnbextension=4.0  # interactive HTML widgets for Jupyter notebooks
  - pip:
    - keras-tuner~=1.1.3  # used in chapters 10 and 19 for hyperparameter tuning
    - tensorboard-plugin-profile~=2.8.0  # profiling plugin for TensorBoard
    - tensorboard~=2.10.0  # TensorFlow's visualization toolkit
    - tensorflow-addons~=0.17.1  # used in chapters 11 & 16 (for AdamW & seq2seq)
    - tensorflow-datasets~=4.6.0  # datasets repository, ready to use
    - tensorflow-hub~=0.12.0  # trained ML models repository, ready to use
    - tensorflow-serving-api~=2.10.0  # or tensorflow-serving-api-gpu if gpu
    - tensorflow~=2.10.0  # Deep Learning library
    - transformers~=4.21.3  # Natural Language Processing lib for TF or PyTorch
    - urlextract~=1.6.0  # optionally used in chapter 3, exercise 4
    - gym[classic_control,atari,accept-rom-license]~=0.26.1  # used only in ch18
    - google-cloud-aiplatform~=1.17.0  # used only in chapter 19
    - google-cloud-storage~=2.5.0  # used only in chapter 19
